/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backupFinder;

import burp.BurpExtender;
import burp.IHttpRequestResponse;
import burp.IRequestInfo;
import burp.IResponseInfo;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author "Moein Fatehi moein.fatehi@gmail.com"
 */
public class BackupFinder extends javax.swing.JPanel {
    private static int sentRequests=0;
    public static List<String> backupFiles_list=new ArrayList<>();
    public static List<String> indexBackupFiles_list=new ArrayList<>();
    private List<String> bruteForce_dict=null;
    
    private static int threads_max=50;
    private static int threads_default=10;
    backup_HTTPrequest[] threadsArr=null;
    
    private static IHttpRequestResponse baseReqResp=null;
    private static IHttpRequestResponse invalidReqResp=null;
    private static int invalidStatus=403;
    private static String indexFile="";
    private static String extension_name="BackupFinder";
    private static String invalidFile="FileDoesNot.Exist";
    private static String dict_file="backup_zipFiles";
    static String[] extensions_level1={"backup","bkup","old","tmp","bak","rar","zip","swp"};
    static String[] extensions_level2={"bkp","temp","txt","tar.gz","tar.xz","bk"};
    static String[] endingChars={"~","2"};
    static String[] backUpChars_level1={"backup","bkup","old","tmp","bak"};
    static String[] backUpChars_level2={"bkp","temp","orgin","original","new","source"};
    static String[] zipChars_level1={"rar","zip"};
    static String[] zipChars_level2={"tar.gz","tar.xz"};
    
    private static List<IHttpRequestResponse> ReqRespList=new ArrayList<>();
    private static List<String> dirsList=new ArrayList<>();
    private static List<String> filesList=new ArrayList<>();
    private static List<String> filesWothoutExt=new ArrayList<>();
    
    
    private static void updateBaseReqRespTable(IHttpRequestResponse reqResp) {
        DefaultTableModel model=(DefaultTableModel)baseReqRespTable.getModel();
        String host=reqResp.getHttpService().getHost();
        int port=reqResp.getHttpService().getPort();
        IRequestInfo reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
        String path=reqInfo.getUrl().getPath();
        String method=reqInfo.getMethod();
        Object rowData[];
        if(reqResp.getResponse()!=null){
            IResponseInfo respInfo=BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse());
            int status=respInfo.getStatusCode();
            int length=reqResp.getResponse().length-respInfo.getBodyOffset();
            rowData=new Object[]{host,port,path,method,status,length};
        }
        else{
            rowData=new Object[]{host,port,path,method,"",""};
        }
        
        if(model.getRowCount()>0){
            model.removeRow(0);
        }
        model.addRow(rowData);
        
    }
    /**
     * Creates new form BackupFinder
     */
    public BackupFinder() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Finder = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        ReqRespTable = new javax.swing.JTable();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        openInBrowserButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        removeStatusButton = new javax.swing.JButton();
        Options = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        baseReqRespTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bruteForce_checkbox = new javax.swing.JCheckBox();
        bruteForce_comboBox = new javax.swing.JComboBox<>();
        bruteForce_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        methodCombobox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invalidStatusField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        invalidFile_TextInBody = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        threadsField = new javax.swing.JTextField();
        threadsErrorLabel = new javax.swing.JLabel();
        throttleField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        threadsErrorLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Extensions_IncludeCheckBox = new javax.swing.JCheckBox();
        Extensions_IncludeField = new javax.swing.JTextField();
        Extensions_ExcludeCheckBox = new javax.swing.JCheckBox();
        Extensions_ExcludeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        status_IncludeCheckBox = new javax.swing.JCheckBox();
        status_IncludeField = new javax.swing.JTextField();
        status_ExcludeCheckBox = new javax.swing.JCheckBox();
        status_ExcludeField = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 147, 0));
        jLabel6.setText("Backup Finder");

        ReqRespTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Host", "Port", "URL", "Method", "Status", "Length"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReqRespTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqRespTableMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(ReqRespTable);
        if (ReqRespTable.getColumnModel().getColumnCount() > 0) {
            ReqRespTable.getColumnModel().getColumn(0).setMinWidth(40);
            ReqRespTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            ReqRespTable.getColumnModel().getColumn(0).setMaxWidth(70);
            ReqRespTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            ReqRespTable.getColumnModel().getColumn(1).setMaxWidth(200);
            ReqRespTable.getColumnModel().getColumn(2).setMinWidth(50);
            ReqRespTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            ReqRespTable.getColumnModel().getColumn(2).setMaxWidth(70);
            ReqRespTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            ReqRespTable.getColumnModel().getColumn(3).setMaxWidth(600);
            ReqRespTable.getColumnModel().getColumn(4).setMinWidth(80);
            ReqRespTable.getColumnModel().getColumn(4).setPreferredWidth(80);
            ReqRespTable.getColumnModel().getColumn(4).setMaxWidth(100);
            ReqRespTable.getColumnModel().getColumn(5).setMinWidth(60);
            ReqRespTable.getColumnModel().getColumn(5).setMaxWidth(80);
            ReqRespTable.getColumnModel().getColumn(6).setMinWidth(60);
            ReqRespTable.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        progressLabel.setText("Progress");

        openInBrowserButton.setText("Open");
        openInBrowserButton.setToolTipText("Open page in browser");
        openInBrowserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openInBrowserButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        removeStatusButton.setText("-Status");
        removeStatusButton.setToolTipText("Remove all rows with the same status as selected row.");
        removeStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinderLayout = new javax.swing.GroupLayout(Finder);
        Finder.setLayout(FinderLayout);
        FinderLayout.setHorizontalGroup(
            FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinderLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FinderLayout.createSequentialGroup()
                        .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressLabel)
                            .addComponent(openInBrowserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        FinderLayout.setVerticalGroup(
            FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(FinderLayout.createSequentialGroup()
                        .addComponent(openInBrowserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeStatusButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Finder", Finder);

        baseReqRespTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Host", "Port", "URL", "Method", "Status", "Length"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        baseReqRespTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baseReqRespTableMouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(baseReqRespTable);
        if (baseReqRespTable.getColumnModel().getColumnCount() > 0) {
            baseReqRespTable.getColumnModel().getColumn(0).setMinWidth(100);
            baseReqRespTable.getColumnModel().getColumn(0).setMaxWidth(200);
            baseReqRespTable.getColumnModel().getColumn(1).setMaxWidth(70);
            baseReqRespTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            baseReqRespTable.getColumnModel().getColumn(2).setMaxWidth(350);
            baseReqRespTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            baseReqRespTable.getColumnModel().getColumn(3).setMaxWidth(120);
            baseReqRespTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            baseReqRespTable.getColumnModel().getColumn(4).setMaxWidth(80);
            baseReqRespTable.getColumnModel().getColumn(5).setPreferredWidth(60);
            baseReqRespTable.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 147, 0));
        jLabel7.setText("Base Request-Response");

        jLabel1.setText("(Double click for details)");

        bruteForce_checkbox.setSelected(true);
        bruteForce_checkbox.setText("Brute-force zip files");

        bruteForce_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default dictionary", "load dictionary" }));
        bruteForce_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bruteForce_comboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Method");

        methodCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAD", "GET" }));
        methodCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodComboboxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 147, 0));
        jLabel8.setText("Not Found Pages");

        jLabel3.setText("Status");

        invalidStatusField.setEditable(false);
        invalidStatusField.setText("404");

        jLabel4.setText("Not-Found text in Response (GET only)");

        invalidFile_TextInBody.setToolTipText("fill if Not-found status is not 404");

        jLabel10.setText("Threads");

        threadsField.setText("10");
        threadsField.setToolTipText("[1,50]");
        threadsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadsFieldActionPerformed(evt);
            }
        });

        threadsErrorLabel.setText("Threads: [1-50]");

        throttleField.setText("0");
        throttleField.setToolTipText("[1,50]");
        throttleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throttleFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Throttle");

        threadsErrorLabel1.setText("Miliseconds");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 147, 0));
        jLabel9.setText("Extensions");

        Extensions_IncludeCheckBox.setText("Include only");

        Extensions_IncludeField.setText("asp,aspx,jsp,php");

        Extensions_ExcludeCheckBox.setSelected(true);
        Extensions_ExcludeCheckBox.setText("Exclude");
        Extensions_ExcludeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extensions_ExcludeCheckBoxActionPerformed(evt);
            }
        });

        Extensions_ExcludeField.setText("js,gif,jpg,png,css,pdf");

        jLabel5.setText("Level");

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 147, 0));
        jLabel13.setText("Status codes");

        status_IncludeCheckBox.setText("Include only");

        status_IncludeField.setText("200");

        status_ExcludeCheckBox.setSelected(true);
        status_ExcludeCheckBox.setText("Exclude");
        status_ExcludeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_ExcludeCheckBoxActionPerformed(evt);
            }
        });

        status_ExcludeField.setText("5xx,3xx,400");

        javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(Options);
        Options.setLayout(OptionsLayout);
        OptionsLayout.setHorizontalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(OptionsLayout.createSequentialGroup()
                        .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addComponent(bruteForce_checkbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bruteForce_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OptionsLayout.createSequentialGroup()
                                        .addComponent(throttleField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(threadsErrorLabel1))
                                    .addComponent(methodCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(OptionsLayout.createSequentialGroup()
                                        .addComponent(threadsField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(threadsErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bruteForce_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(OptionsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invalidStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invalidFile_TextInBody))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(OptionsLayout.createSequentialGroup()
                        .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addComponent(Extensions_IncludeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Extensions_IncludeField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Extensions_ExcludeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Extensions_ExcludeField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addGroup(OptionsLayout.createSequentialGroup()
                                .addComponent(status_IncludeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status_IncludeField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(status_ExcludeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status_ExcludeField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        OptionsLayout.setVerticalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bruteForce_checkbox)
                    .addComponent(bruteForce_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bruteForce_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(methodCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(threadsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threadsErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(throttleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threadsErrorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(invalidStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(invalidFile_TextInBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Extensions_ExcludeCheckBox)
                        .addComponent(Extensions_ExcludeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Extensions_IncludeCheckBox)
                        .addComponent(Extensions_IncludeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_ExcludeCheckBox)
                        .addComponent(status_ExcludeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_IncludeCheckBox)
                        .addComponent(status_IncludeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", Options);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void baseReqRespTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseReqRespTableMouseClicked
        if(evt.getClickCount()==2){
            if(baseReqResp!=null){
                reqRespForm.setReqResp(baseReqResp);
                reqRespForm jf=new reqRespForm();
                jf.setLocation(jSeparator1.getLocationOnScreen());
                jf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                jf.setVisible(true);
            }
        }
    }//GEN-LAST:event_baseReqRespTableMouseClicked

    private void ReqRespTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqRespTableMouseClicked
        if(evt.getClickCount()==2){
            int index=(int)ReqRespTable.getValueAt(ReqRespTable.getSelectedRow(), 0)-1;
            if(ReqRespList.get(index)!=null){
                reqRespForm.setReqResp(ReqRespList.get(index));
                reqRespForm jf=new reqRespForm();
                jf.setLocationRelativeTo(null);
                jf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                jf.tabs.setSelectedIndex(1);
                jf.setVisible(true);
            }
        }
    }//GEN-LAST:event_ReqRespTableMouseClicked

    private void bruteForce_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bruteForce_comboBoxActionPerformed
        int ind=bruteForce_comboBox.getSelectedIndex();
        if(ind==0){ 
            try {
            //Default dict
            bruteForce_dict=Functions.ReadFile(dict_file);
            bruteForce_Label.setText("Default dictionary loaded with "+bruteForce_dict.size()+" entries)");
            } catch (IOException ex) {
                Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(ind==1){ // User's dictionary
            bruteForce_dict=loadFile();
            bruteForce_Label.setText("User's dictionary loaded with "+bruteForce_dict.size()+" entries)");
        }
    }//GEN-LAST:event_bruteForce_comboBoxActionPerformed

    private void methodComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodComboboxActionPerformed
        if(methodCombobox.getSelectedItem().toString().equals("HEAD")){
            invalidFile_TextInBody.setEnabled(false);
        }
        else{
            invalidFile_TextInBody.setEnabled(true);
        }
    }//GEN-LAST:event_methodComboboxActionPerformed

    private void openInBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openInBrowserButtonActionPerformed
        if(ReqRespTable.getSelectedRow()>=0){
            int index=(int)ReqRespTable.getValueAt(ReqRespTable.getSelectedRow(), 0)-1;
            URL url=BurpExtender.callbacks.getHelpers().analyzeRequest(ReqRespList.get(index)).getUrl();
            Functions.openWebpage(url);
        }
    }//GEN-LAST:event_openInBrowserButtonActionPerformed

    private void threadsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadsFieldActionPerformed
        String text=threadsField.getText();
        try {
            int num=Integer.parseInt(text);
            if(num>threads_max){
                num=threads_max;
                threadsField.setText(""+threads_max);
                threadsErrorLabel.setText("Max thread num: "+threads_max);
            }
            else if(num<1){
                num=1;
                threadsField.setText(""+1);
                threadsErrorLabel.setText("Min thread num: "+1);
            }
            else{
                threadsField.setText(""+num);
                threadsErrorLabel.setText("");
            }

        } catch (Exception e) {
            threadsErrorLabel.setText("Invalid Thread Num (1<=thread<=50");
            fixThreadNum();
        }
    }//GEN-LAST:event_threadsFieldActionPerformed

    private void throttleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throttleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_throttleFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        
        resetFields();
        sentRequests=0;
        if(baseReqResp!=null){
            categorizeSitemap();
            categorizeHistory();
        }
        findIndexFileActively();
        testforIndexFiles();
        generatePayloads(baseReqResp);
        //printList(backupFiles_list);
        sendRequests(backupFiles_list);
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void Extensions_ExcludeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extensions_ExcludeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Extensions_ExcludeCheckBoxActionPerformed

    private void status_ExcludeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_ExcludeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_ExcludeCheckBoxActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        for (int i = 0; i < threadsArr.length; i++) {
            threadsArr[i].getThread().stop();
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void removeStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStatusButtonActionPerformed
        if(ReqRespTable.getSelectedRow()>=0){
            int index=(int)ReqRespTable.getValueAt(ReqRespTable.getSelectedRow(), 0)-1;
            int status=BurpExtender.callbacks.getHelpers().analyzeResponse(ReqRespList.get(index).getResponse()).getStatusCode();
            status_ExcludeField.setText(status_ExcludeField.getText()+","+status);
            
            for(int i=ReqRespTable.getRowCount()-1;i>=0;i--){
                if((int)ReqRespTable.getValueAt(i, 5)==status){
                    removeTableRow(i);
                }
            }
        }
        
        
    }//GEN-LAST:event_removeStatusButtonActionPerformed
    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Extensions_ExcludeCheckBox;
    private javax.swing.JTextField Extensions_ExcludeField;
    private javax.swing.JCheckBox Extensions_IncludeCheckBox;
    private javax.swing.JTextField Extensions_IncludeField;
    private javax.swing.JPanel Finder;
    private javax.swing.JPanel Options;
    public static javax.swing.JTable ReqRespTable;
    public static javax.swing.JTable baseReqRespTable;
    private javax.swing.JLabel bruteForce_Label;
    private javax.swing.JCheckBox bruteForce_checkbox;
    private javax.swing.JComboBox<String> bruteForce_comboBox;
    private static javax.swing.JTextField invalidFile_TextInBody;
    private static javax.swing.JTextField invalidStatusField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JComboBox<String> levelComboBox;
    public static javax.swing.JComboBox<String> methodCombobox;
    private javax.swing.JButton openInBrowserButton;
    private static javax.swing.JProgressBar progressBar;
    private static javax.swing.JLabel progressLabel;
    private javax.swing.JButton removeStatusButton;
    private javax.swing.JButton startButton;
    private static javax.swing.JCheckBox status_ExcludeCheckBox;
    private static javax.swing.JTextField status_ExcludeField;
    private static javax.swing.JCheckBox status_IncludeCheckBox;
    private static javax.swing.JTextField status_IncludeField;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel threadsErrorLabel;
    private javax.swing.JLabel threadsErrorLabel1;
    private static javax.swing.JTextField threadsField;
    private static javax.swing.JTextField throttleField;
    // End of variables declaration//GEN-END:variables

    public static IHttpRequestResponse getBaseReqResp(){
        return baseReqResp;
    }
    public static void setBaseReqResp(IHttpRequestResponse reqResp){
        baseReqResp=reqResp;
        updateBaseReqRespTable(reqResp);
        sendInvalidRequest(reqResp);
    }
    public static String getInvalidFileName(){
        return invalidFile;
    }
    public static int getInvalidStatus(){
        return invalidStatus;
    }
    
    public static void setInvalidStatus(int status){
        invalidStatus=status;
        invalidStatusField.setText(""+status);
    }
    
    public static IHttpRequestResponse getInvalidReqResp(){
        return invalidReqResp;
    }
    public static void setInvalidReqResp(IHttpRequestResponse reqResp){
        invalidReqResp=reqResp;
        setInvalidStatus(BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse()).getStatusCode());
    }
    
    public static void sendInvalidRequest(IHttpRequestResponse reqResp){
        List<String> invalidfile=new ArrayList<>();
        invalidfile.add("/"+invalidFile);
        backup_HTTPrequest bhr=new backup_HTTPrequest(reqResp, invalidfile, (String) methodCombobox.getSelectedItem(),1);
        bhr.start();
    }
    
    public static void addToTable(IHttpRequestResponse reqResp) {
        IRequestInfo reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
        if(canBeAddedToTable(reqResp)){
            IResponseInfo respInfo=BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse());
            DefaultTableModel model=(DefaultTableModel)ReqRespTable.getModel();
            String host=reqResp.getHttpService().getHost();
            int port=reqResp.getHttpService().getPort();
            String path=reqInfo.getUrl().getPath();
            String method=reqInfo.getMethod();
            int status=respInfo.getStatusCode();
            int length=reqResp.getResponse().length-respInfo.getBodyOffset();
            Object rowData[]=new Object[]{ReqRespTable.getRowCount()+1,host,port,path,method,status,length};
            model.addRow(rowData);
            ReqRespList.add(reqResp);
        }
    }

    private void generatePayloads(IHttpRequestResponse reqResp) {
        addListToList(backupFiles_list, generateRootDirectoryPayloads(reqResp));
        addListToList(backupFiles_list, generatePayloadForDirs(dirsList));
        addListToList(backupFiles_list, generatePayloadForFiles(filesList));
        addListToList(backupFiles_list, generatePayloadForFilesWithoutExtension(filesWothoutExt));
    }
    
    public static boolean fileIsUnique(String backupFile) {
        for (int i = 0; i < ReqRespTable.getRowCount(); i++) {
            if(ReqRespTable.getValueAt(i, 3).equals(backupFile)){
                return false;
            }
        }
        return true;
    }
    
    private List<String> loadFile(){
        List<String> dict=new ArrayList<String>();
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        try {
            Scanner reader = new Scanner(fc.getSelectedFile());
            while(reader.hasNextLine()){
                dict.add(reader.nextLine());
            }
        } catch (FileNotFoundException ex) {
            bruteForce_Label.setText("Error loading file");
        }
        return dict;
    }
    
    private void initialize() {
        resetFields();
        levelComboBox.setSelectedIndex(2); //Level:3
        try {
            bruteForce_dict=Functions.ReadFile(dict_file);
        } catch (IOException ex) {
            Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(ReqRespTable.getModel());
        ReqRespTable.setRowSorter(sorter);
        
    }
    public static int getSentRequests(){
        return sentRequests;
    }
    public static void increaseSentRequests(){
        sentRequests++;
        progressBar.setMaximum(backupFiles_list.size()+indexBackupFiles_list.size());
        progressBar.setValue(getSentRequests());
        progressLabel.setText("("+getSentRequests()+"/"+(backupFiles_list.size()+indexBackupFiles_list.size())+")");
    }
    
    public static String getInvalidFile_ErrorText(){
        return invalidFile_TextInBody.getText();
    }
    
    public static String getExtensionName(){
        return extension_name;
    }
    
    private void resetFields() {
        backupFiles_list=new ArrayList<>();
        indexBackupFiles_list=new ArrayList<>();
        ReqRespList=new ArrayList<>();
        filesList=new ArrayList<>();
        dirsList=new ArrayList<>();
        filesWothoutExt=new ArrayList<>();
        sentRequests=0;
        DefaultTableModel model=(DefaultTableModel)ReqRespTable.getModel();
        for (int i = model.getRowCount()-1; i >=0; i--) {
            model.removeRow(i);
        }
    }
    
    private List<String> readCommonFiles() {
        try {
            return Functions.ReadFile("root_commonFiles");
        } catch (IOException ex) {
            Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private void fixThreadNum() {
        String num=threadsField.getText();
        String fixed="";
        for (int i = 0; i < num.length(); i++) {
            try {
                fixed+=Integer.parseInt(num.charAt(i)+"");
            } catch (Exception e) {
            }
        }
        threadsField.setText(fixed);
    }
    
    private static int getThreads(){
        try {
            return Integer.parseInt(threadsField.getText());
        } catch (Exception e) {
            return threads_default;
        }
    }
    
    public static int getThrottle(){
        try {
            return Integer.parseInt(throttleField.getText());
        } catch (Exception e) {
            return 0;
        }
    }

    private void sendRequests(List<String> list) {
        int each=list.size()/getThreads()+1;
        int end=0;
        threadsArr=new backup_HTTPrequest[getThreads()];
        for (int i = 0; i < getThreads(); i++) {
            end=Math.min((i+1)*each, list.size());
            List<String> temp=list.subList(i*each, end);
            backup_HTTPrequest bhr=new backup_HTTPrequest(getBaseReqResp(), temp, (String) methodCombobox.getSelectedItem(),3);
            threadsArr[i]=bhr;
            threadsArr[i].start();
        }
    }

    public static List<String> addListToList(List<String> list1, List<String> list2) {
        
        for (String list2element : list2) {
            list1.add(list2element);
        }
        return list1;
    }

    private static void findIndexFilePassively(String thisPath) {
        if(indexFile.length()==0){
            String fileName=thisPath.substring(thisPath.lastIndexOf("/")+1);
            if (fileName.startsWith("index.")){
                String[] ext={"php","aspx","asp","jsp"};
                for (int i = 0; i < ext.length; i++) {
                    if(fileName.equals("index."+ext[i])){
                        indexFile="index."+ext[i];
                    }
                }
            }
        }
        
    }
    public static void setIndexFile(String file){
        indexFile=file;
    }
    
    private static String getFileFromPath(String path){
        return path.substring(path.lastIndexOf("/")).replace("/", "");
    }
    
    private static String getFileName(String file){
        if(file.contains(".")){
            return file.substring(0,file.indexOf("."));
        }
        else{
            return file;
        }
    }
    
    private static String getFileExtension(String file){
        if(file.contains(".")){
            return file.substring(file.indexOf(".")).replace(".", "");
        }
        else{
            return "";
        }
    }
    
    private static String getLastDirFromPath(String path){
        System.out.println(path.lastIndexOf("/"));
        String p=path.substring(0,path.lastIndexOf("/"));
        System.out.println("##p: "+p);
        if(p.length()>0){  //string has more than 1 subdirectry "/"
            return p.substring(p.lastIndexOf("/")).replace("/", "");
        }
        else{
            return "";
        }
    }
    

    private void printList(List<String> backupFiles_list) {
        BufferedWriter out = null;
        try {
            
            String userHomeFolder = System.getProperty("user.home");
            File textFile = new File(userHomeFolder, "list.txt");
            out = new BufferedWriter(new FileWriter(textFile));
            out.flush();
            try {
                for (String string : backupFiles_list) {
                    out.write(string+"\n");
                }
            } finally {
                out.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void printSiteMap(String str) {
        BufferedWriter out = null;
        try {
            String userHomeFolder = System.getProperty("user.home");
            File textFile = new File(userHomeFolder, "list2.txt");
            out = new BufferedWriter(new FileWriter(textFile,true));
            out.flush();
            try {
                out.append(str+"\n");
            } finally {
                out.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean addToDirsList(String thisPath) {
        for (String dir : dirsList) {
            if(thisPath.equals(dir)){
                return false;
            }
        }
        dirsList.add(thisPath);
        return true;
    }
    
    private boolean addToFilesList(String thisPath) {
        if(extensionIsValid(thisPath)){
            findIndexFilePassively(thisPath);
            for (String file : filesList) {
                if(thisPath.equals(file)){
                    return false;
                }
            }
            filesList.add(thisPath);
        }
        return true;
    }
    private boolean addTofilesWothoutExt(String thisPath) {
        for (String file : filesWothoutExt) {
            if(thisPath.equals(file)){
                return false;
            }
        }
        filesWothoutExt.add(thisPath);
        return true;
    }
    
    private boolean extensionIsValid(String thisPath){
        String ext=Functions.getExtension(thisPath);
        if (Extensions_ExcludeCheckBox.isSelected()){
            Scanner sc = new Scanner(Extensions_ExcludeField.getText());
            sc.useDelimiter(",");
            while (sc.hasNext()){
                if(ext.equals(sc.next())){
                    return false;
                }
            }
        }
        if (Extensions_IncludeCheckBox.isSelected()){
            Scanner sc = new Scanner(Extensions_IncludeField.getText());
            sc.useDelimiter(",");
            while (sc.hasNext()){
                if(ext.equals(sc.next())){
                    return true;
                }
            }
            return false;
        }
        return true;
    }

    private void categorizeSitemap() {
        URL url=BurpExtender.callbacks.getHelpers().analyzeRequest(baseReqResp).getUrl();
        String start=url.getProtocol()+"://"+url.getHost();
        if(getBaseReqResp().getHttpService().getPort()!=80&&getBaseReqResp().getHttpService().getPort()!=443){
            start=start+":"+getBaseReqResp().getHttpService().getPort();
        }
        IHttpRequestResponse[] siteMap=BurpExtender.callbacks.getSiteMap(start);
        String before="zzzzzzzzz";
        IHttpRequestResponse beforeReqResp=null;
        for (IHttpRequestResponse reqResp : siteMap) {
            IRequestInfo reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
            if(reqResp.getHttpService().getHost().equals(getBaseReqResp().getHttpService().getHost())){
                if(reqResp.getHttpService().getPort()==getBaseReqResp().getHttpService().getPort()){
                    String thisPath=Functions.getURL(reqResp).getPath();
                    if(!thisPath.equals(before)){
                        if(thisPath.contains("/")){
                            String endpart=thisPath.substring(thisPath.lastIndexOf("/")).replace("/", "");
                            if(endpart.length()==0){    //thisPath ends with "/"
                                addToDirsList(thisPath);
                                if(thisPath.equals(before+"/")){
                                    filesWothoutExt.remove(before);
                                }
                            }
                            else if(endpart.contains(".")){ //it's a file with extension
                                addToFilesList(thisPath);
                            }
                            else {
                                reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
                                if(reqResp.getResponse()!=null){
                                    IResponseInfo respInfo=BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse());
                                    if(respInfo.getStatusCode()/100!=3){
                                        addTofilesWothoutExt(thisPath);
                                    }
                                }
                            }
                        }
                    }
                    beforeReqResp=reqResp;
                    before=Functions.getURL(reqResp).getPath();
                }
            }
        }
    }
    
    private void categorizeHistory() {
        URL url=BurpExtender.callbacks.getHelpers().analyzeRequest(baseReqResp).getUrl();
        String start=url.getProtocol()+"://"+url.getHost();
        if(getBaseReqResp().getHttpService().getPort()!=80&&getBaseReqResp().getHttpService().getPort()!=443){
            start=start+":"+getBaseReqResp().getHttpService().getPort();
        }
        IHttpRequestResponse[] history=BurpExtender.callbacks.getProxyHistory();
        String before="zzzzzzzzz";
        IHttpRequestResponse beforeReqResp=null;
        for (IHttpRequestResponse reqResp : history) {
            IRequestInfo reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
            if(reqResp.getHttpService().getHost().equals(getBaseReqResp().getHttpService().getHost())){
                if(reqResp.getHttpService().getPort()==getBaseReqResp().getHttpService().getPort()){
                    String thisPath=Functions.getURL(reqResp).getPath();
                    if(thisPath.contains("/")){
                        String endpart=thisPath.substring(thisPath.lastIndexOf("/")).replace("/", "");
                        if(endpart.length()==0){    //thisPath ends with "/"
                            addToDirsList(thisPath);
                        }
                        else if(endpart.contains(".")){ //it's a file with extension
                            addToFilesList(thisPath);
                        }
                        else {
                            reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
                        if(reqResp.getResponse()!=null){
                            IResponseInfo respInfo=BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse());
                            if(respInfo.getStatusCode()/100!=3){
                                addTofilesWothoutExt(thisPath);
                            }
                        }
                        }
                    }
                    beforeReqResp=reqResp;
                    before=Functions.getURL(reqResp).getPath();
                }
            }
            
        }
    }

    public static String getIndexFile(){
        return indexFile;
    }
    
    private void findIndexFileActively() {
        if(indexFile.length()==0){
            for (String dir : dirsList) {
                List<String>indexes=new ArrayList<>();
                if(indexFile.length()==0){
                    String[] ext={"php","aspx","asp","jsp"};
                    for (int i = 0; i < ext.length; i++) {
                        indexes.add(dir+"index."+ext[i]);
                    }
                }
                
                backup_HTTPrequest bhr=new backup_HTTPrequest(getBaseReqResp(), indexes, (String) methodCombobox.getSelectedItem(),2);
                bhr.start();
                
            }
        }
    }

    private void testforIndexFiles() {
        if(indexFile.length()!=0){
            List<String>indexes=new ArrayList<>();
            for (String dir : dirsList) {
                if(!filesList.contains(dir+getIndexFile())){
                    indexes.add(dir+getIndexFile());
                }
            }
            backup_HTTPrequest bhr=new backup_HTTPrequest(getBaseReqResp(), indexes, (String) methodCombobox.getSelectedItem(),4);
            bhr.start();
        }
    }
    
    public static void addIndexFilesToList(String path){
        filesList.add(path);
    }

    private static int getLevel(){
        return levelComboBox.getSelectedIndex()+1;
    }
    
    private List<String> generateRootDirectoryPayloads(IHttpRequestResponse reqResp) {
        List<String> backupList=new ArrayList<String>();
        String hostName=reqResp.getHttpService().getHost();
        List<String>subdomains=new ArrayList<>();
        
        if(hostName.contains(".")){
            Scanner sc=new Scanner(hostName);
            sc.useDelimiter("\\.");
            while(sc.hasNext()){
                subdomains.add(sc.next());
            }
            String h2=hostName;
            while (h2.contains(".")){
                h2=h2.substring(0,h2.lastIndexOf("."));
                if(!subdomains.contains(h2)){
                    subdomains.add(h2);
                }
            }
        }
        
        //+++++++++++++++++++++++++
        //files to be checked in root direcroty
        //checking subdirectories as zip files
        for (int i = 0; i < zipChars_level1.length; i++) {
            backupList.add("/"+hostName+"."+zipChars_level1[i]);    //www.site.com/www.site.com.rar
            if(subdomains.size()>0){
                for (String subdomain : subdomains) {
                    backupList.add("/"+subdomain+"."+zipChars_level1[i]);    //site.rar,www.rar
                }
            }
            for (int num = 1; num < 3; num++) {
                for (String subdomain : subdomains) {
                    backupList.add("/"+subdomain+num+"."+zipChars_level1[i]); //site1.rar,site2.zip
                }
            }
        }
        //Level2 and Level3
        if(getLevel()>1){
            for (int i = 0; i < zipChars_level2.length; i++) {
                backupList.add("/"+hostName+"."+zipChars_level2[i]);    //www.site.com/www.site.com.rar
                if(subdomains.size()>0){
                    for (String subdomain : subdomains) {
                        backupList.add("/"+subdomain+"."+zipChars_level2[i]);    //site.rar,www.rar
                    }
                }
                for (int num = 1; num < 3; num++) {
                    for (String subdomain : subdomains) {
                        backupList.add("/"+subdomain+num+"."+zipChars_level2[i]); //site1.rar,site2.zip
                    }
                }
            }
        }
        //checking common files and directories in root directory
        for (String commonFile : readCommonFiles()) {
            backupList.add("/"+commonFile);       //site.com/error_log
        }
        
        //checking common zip files in root directory
        if(bruteForce_checkbox.isSelected() && bruteForce_dict!=null){
            for (int i = 0; i < bruteForce_dict.size(); i++) {
                for (int j = 0; j < zipChars_level1.length; j++) {
                    backupList.add("/"+bruteForce_dict.get(i)+"."+zipChars_level1[j]);    //Edit to root
                }
                //Level2 and above
                if(getLevel()>1){
                    for (int j = 0; j < zipChars_level2.length; j++) {
                        backupList.add("/"+bruteForce_dict.get(i)+"."+zipChars_level2[j]);    //Edit to root
                    }
                }
            }
        }
        return backupList;
    }
    
    private List<String> generatePayloadForDirs(List<String> dirs) {
         //+++++++++++++++++++++++++
        //payloads for directories:
        List<String> backupList=new ArrayList<String>();
        dirs.remove("/");
        for (String dir : dirs) {
            String lastDir=getLastDirFromPath(dir);
            for (String zipChar : zipChars_level1) {
                backupList.add(dir+lastDir+"."+zipChar);
                String dir2=dir.substring(0,dir.lastIndexOf("/"));   //Dir without ending slash
                backupList.add(dir2+"."+zipChar);
                for (int i = 2; i < 4; i++) {
                    backupList.add(dir2+i+"."+zipChar);
                }
            }
            //Level 2 and above
            if(getLevel()>=2){
                for (String zipChar : zipChars_level2) {
                    backupList.add(dir+lastDir+"."+zipChar);
                    String dir2=dir.substring(0,dir.lastIndexOf("/"));   //Dir without ending slash
                    backupList.add(dir2+"."+zipChar);
                    for (int i = 2; i < 4; i++) {
                        backupList.add(dir2+i+"."+zipChar);
                    }
                }
            }
            //Level 3
            if(getLevel()>=3){
                try {
                    //checking common files and directories in each directory
                    List<String> files=Functions.ReadFile("dir_commonFiles");
                    for (String commonFile : files) {
                        backupList.add(dir+commonFile);       //site.com/dir/error_log
                    }
                } catch (IOException ex) {
                    Logger.getLogger(BackupFinder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(getLevel()>=4){
                //checking common zip files in root directory
                if(bruteForce_checkbox.isSelected() && bruteForce_dict!=null){
                    for (String file: bruteForce_dict) {
                        for (int j = 0; j < zipChars_level1.length; j++) {
                            backupList.add(dir+file+"."+zipChars_level1[j]);
                        }
                        //Level5 and above
                        if(getLevel()>=5){
                            for (int j = 0; j < zipChars_level2.length; j++) {
                                backupList.add(dir+file+"."+zipChars_level2[j]);    //Edit to root
                            }
                        }
                    }
                }
            }
            
        }
        return backupList;
    }

    public static List<String> generatePayloadForFiles(List<String> files) {
        //+++++++++++++++++++++++++
        //payloads for files with extension:
        List<String> backupList=new ArrayList<String>();
        for (String file: files){
            String name=file.substring(0,file.lastIndexOf("."));
            //Level1 (Base)
            for (String extension:extensions_level1) {
                backupList.add(file+"."+extension);
                //Level2 and above
                if(getLevel()>=2){
                   backupList.add(name+"."+extension);
                }
                
            }
            //Same for all Levels
            //Adds some ending chars like "2" and "~" to end of file
            for (String endingChar : endingChars) {
                backupList.add(file+endingChar);
            }
            
            for (String backupChar : backUpChars_level1) {
                backupList.add(file+"-"+backupChar);
                backupList.add(file+"_"+backupChar);
                //Level2 and above
                if(getLevel()>=2){
                    backupList.add(name+"-"+backupChar);
                    backupList.add(name+"_"+backupChar);
                }
                
            }
            
            //Level2 and above
            if(getLevel()>=2){
                for (String extension:extensions_level2) {
                    backupList.add(file+"."+extension);
                    //Level3 and above
                    if(getLevel()>=3){
                        backupList.add(name+"."+extension);
                    }
                }
                
                for (String backupChar : backUpChars_level2) {
                    backupList.add(file+"-"+backupChar);
                    backupList.add(file+"_"+backupChar);
                    //Level3 and above
                    if(getLevel()>=3){
                        backupList.add(name+"-"+backupChar);
                        backupList.add(name+"_"+backupChar);
                    }
                    
                }
            }
            
            
        }
        return backupList;
    }

    private List<String> generatePayloadForFilesWithoutExtension(List<String> filesWE) {
        //+++++++++++++++++++++++++
        //payloads for files without extension:
        List<String> backupList=new ArrayList<String>();
        for (String filewe: filesWE){
            
            //Level1 (Base)
            for (String endingChar : endingChars) {
                backupList.add(filewe+endingChar);
            }
            
            for (String extension:extensions_level1) {
                backupList.add(filewe+"."+extension);
            }
            //Level2 and above
            if (getLevel()>=2){
                for (String extension:extensions_level2) {
                    backupList.add(filewe+"."+extension);
                }
                for (String backupChar : backUpChars_level1) {
                    backupList.add(filewe+"-"+backupChar);
                    //Level3 and above
                    if (getLevel()>=3){
                        backupList.add(filewe+"_"+backupChar);
                    }
                }
            }
            
        }
        return backupList;
    }

    private void addToMainList(List<String> generateRootDirectoryPayloads) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private static boolean canBeAddedToTable(IHttpRequestResponse reqResp) {
        IRequestInfo reqInfo=BurpExtender.callbacks.getHelpers().analyzeRequest(reqResp);
        if(fileIsUnique(reqInfo.getUrl().getPath())){   // file is not repetetive
            if(StatusCodeIsOK(reqResp)){
                return true;
            }
        }
        return false;
    }
    
    private static boolean StatusCodeIsOK(IHttpRequestResponse reqResp) {
        int status=BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse()).getStatusCode();
        String statusStr=""+status;
        if (status_ExcludeCheckBox.isSelected()){
            Scanner sc = new Scanner(status_ExcludeField.getText());
            sc.useDelimiter(",");
            while (sc.hasNext()){
                String thisCode=sc.next();
                thisCode=thisCode.replaceAll("x", "");
                if(statusStr.startsWith(thisCode)&&thisCode.length()<=3){
                    return false;
                }
            }
        }
        if (status_IncludeCheckBox.isSelected()){
            Scanner sc = new Scanner(status_IncludeField.getText());
            sc.useDelimiter(",");
            while (sc.hasNext()){
                String thisCode=sc.next();
                thisCode=thisCode.replaceAll("x", "");
                if(statusStr.startsWith(thisCode)&&thisCode.length()<=3){
                    return true;
                }
            }
            return false;
        }
        return true;
    }
    
    
    public static boolean responseIsNotFoundPage(IHttpRequestResponse reqResp){
        if(BackupFinder.getInvalidStatus()!=200){
            if(BurpExtender.callbacks.getHelpers().analyzeResponse(reqResp.getResponse()).getStatusCode()==BackupFinder.getInvalidStatus()){
                return true;
            }
        }
        else{
            if (getInvalidFile_ErrorText().length()>0&&responseContainsErrorString(reqResp)){
                return true;
            }
        }
        return false;
    }
    
    private static boolean responseContainsErrorString(IHttpRequestResponse reqResp) {
        if (Functions.findRegex(getInvalidFile_ErrorText(), new String (reqResp.getResponse()))!=null){
            return true;
        }
        return false;
    }

    private void removeTableRow(int i) {
        DefaultTableModel tableModel=(DefaultTableModel)ReqRespTable.getModel();
        int thisInd=ReqRespTable.convertRowIndexToModel(i);
        tableModel.removeRow(thisInd);
        ReqRespList.remove(thisInd);
        
        updateRowNumbers();
    }

    private void updateRowNumbers() {
        DefaultTableModel model=(DefaultTableModel)ReqRespTable.getModel();
        for (int i = 0; i < ReqRespTable.getRowCount(); i++) {
            model.setValueAt(i+1, i, 0);
        }
    }
}
