/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backupFinder;

import burp.BurpExtender;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author "Moein Fatehi moein.fatehi@gmail.com"
 */
public class HelpPanel extends javax.swing.JPanel {

    /**
     * Creates new form HelpPanel
     */
    public HelpPanel() {
        initComponents();
        update_About_Tab();
    }
    
    private void update_About_Tab() {
        //set version
        aboutTable.setValueAt(BurpExtender.getVersion(), 0, 1);
        //set project name
        aboutTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(BurpExtender.getProjectName());
        Calendar calendar = new GregorianCalendar();
        int year = calendar.get(Calendar.YEAR);
        aboutTable.setValueAt("© "+(year-1)+"-"+year+" Moein Fatehi", 5, 1);
        try {
            editorPane.setText(ReadFile("instruction"));
        } catch (IOException ex) {
            Logger.getLogger(HelpPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        descField.setText(descField.getText().replace("{extension name}", BurpExtender.getProjectName()));
    }
    
    public String ReadFile(String filename) throws IOException {
        String content="";
        BufferedReader br = null;
        try {
            InputStream inputStream = getClass().getResourceAsStream("/files/"+filename);
            InputStreamReader streamReader = new InputStreamReader(inputStream, "UTF-8");
            br = new BufferedReader(new InputStreamReader(inputStream));
        } catch (Exception e) {
            BurpExtender.output.println("File not Found");
            return null;
        }
        try {
            String line = br.readLine();
            while (line != null) {
                content+=line+"\n";
                line = br.readLine();
            }
        } finally {
            br.close();
        }
        return content;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        aboutPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        aboutTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();

        editorPane.setEditable(false);
        editorPane.setContentType("text/html"); // NOI18N
        jScrollPane7.setViewportView(editorPane);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Instruction", jPanel8);

        aboutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Version", "0.1"},
                {"Creator", "Moein Fatehi"},
                {"Email", "moein.fatehi@gmail.com"},
                {"Website", "moeinfatehi.ir"},
                {"Twitter", "@MoeinFatehi"},
                {"Copyright", "© 2015-2016 Moein Fatehi"}
            },
            new String [] {
                "Project", "Input Fuzzer"
            }
        ));
        jScrollPane8.setViewportView(aboutTable);

        jLabel11.setText("Short description");

        descField.setEditable(false);
        descField.setColumns(20);
        descField.setLineWrap(true);
        descField.setRows(5);
        descField.setText("{extension name} is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\nIf you have any questions or suggestions, feel free to contact me via my twitter account.");
        descField.setWrapStyleWord(true);
        jScrollPane9.setViewportView(descField);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("About", aboutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTable aboutTable;
    private javax.swing.JTextArea descField;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
