/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backupFinder;

import burp.BurpExtender;
import burp.IBurpExtenderCallbacks;
import burp.IHttpRequestResponse;
import burp.IHttpService;
import burp.IMessageEditor;
import burp.IMessageEditorController;
import burp.IRequestInfo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moein
 */
public class reqRespForm extends javax.swing.JFrame implements IMessageEditorController{

    DefaultTableModel model;
    private static IHttpRequestResponse thisReqResp;
    private IMessageEditor requestViewer;
    private IMessageEditor responseViewer;
    private IBurpExtenderCallbacks callbacks=BurpExtender.callbacks;
    /**
     * Creates new form NewJFrame
     */
    public reqRespForm() {
        initComponents();
        try {
            requestViewer = callbacks.createMessageEditor(this, false);
            responseViewer = callbacks.createMessageEditor(this, false);
            tabs.addTab("Request", requestViewer.getComponent());
            tabs.addTab("Response", responseViewer.getComponent());
            requestViewer.setMessage(thisReqResp.getRequest(), true);
            responseViewer.setMessage(thisReqResp.getResponse(), false);
        } catch (Exception e) {
            BurpExtender.output.println("Exception");
            BurpExtender.output.println(e.getMessage());
            BurpExtender.output.println(e.toString());
        }
        setTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reqRespForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reqRespForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reqRespForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reqRespForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reqRespForm().setVisible(true);
            }
        });
    }
    
    public static void setReqResp(IHttpRequestResponse reqResp){
        thisReqResp= reqResp;
    }
    
    @Override
    public IHttpService getHttpService() {
        return thisReqResp.getHttpService();
    }

    @Override
    public byte[] getRequest() {
        
        return thisReqResp.getRequest();
    }

    @Override
    public byte[] getResponse() {
        return thisReqResp.getResponse();
    }

    private void setTitle() {
        IHttpService serv=thisReqResp.getHttpService();
        IRequestInfo reqInfo = callbacks.getHelpers().analyzeRequest(thisReqResp);
        this.setTitle(reqInfo.getMethod()+" request to "+reqInfo.getUrl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
